'''
In Python, the Dictionary data types represent the implementation of hash tables. The Keys in the dictionary satisfy the following requirements.
The keys of the dictionary are hashable i.e. the are generated by hashing function which generates unique result for each unique value supplied to the hash function.
The order of data elements in a dictionary is not fixed.
So we see the implementation of hash table by using the dictionary data types
'''

# accessing data with keys in hash table :
hash_table = {1 :'one', 2 : 'two', 3 : 'three', 4 : 'four'} 

hash_table[1] # -> one
hash_table[4] # -> four

#adding items:
hash_table[5] = 'five'

# updating dictionary:
hash_table[4] = 'FOUR'
print(hash_table)

#deleting items:
del hash_table[1]   # remove entry with key 'Name'
hash_table.clear();     # remove all entries in dict
del hash_table ;        # delete entire dictionary
